name: InfinityExpansion
author: Mooy1
description: 黏液科技附加 無限附加 繁體翻譯版.
main: io.github.mooy1.infinityexpansion.InfinityExpansion
website: https://github.com/Mooy1/InfinityExpansion
depend: [Slimefun]
softdepend: [LiteXpansion]
version: ${project.version}
api-version: 1.16

commands:
  infinityexpansion:
    description: Do /infinityexpansion help for a list of commands
    usage: /infinityexpansion <subcommand>
    aliases: [ie, ix, infinity]
